apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: aXJlbmVzYWx2bw== #irenesalvo
  MONGO_INITDB_ROOT_USERNAME: cHJvZ2V0dG9EU0JEMjAyMQ== #progettoDSBD2021
kind: Secret
metadata:
 name: orders-service-db-secret-file
 namespace: default
type: Opaque
